export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const RETRIEVE_ARTICLES = "RETRIEVE_ARTICLES";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ALL_ARTICLES = "DELETE_ALL_ARTICLES";

export const RETRIEVE_TYPES_REMPLACEMENTS = "RETRIEVE_TYPES_REMPLACEMENTS";
export const RETRIEVE_TYPES_ARTICLES = "RETRIEVE_TYPES_ARTICLES";
export const RETRIEVE_TYPES_DLC = "RETRIEVE_TYPES_DLC";
export const RETRIEVE_TYPES_ANIMALES = "RETRIEVE_TYPES_ANIMALES";